### ISSUE TITLE
[RFE] check container help file inside image in roff format

### ISSUE THREAD

**Issue by phracek** [user-cont/conu#100]
Nowadays, MTF uses help.md (Markdown) format for testing some sanity checks.
https://github.com/fedora-modularity/meta-test-family/blob/devel/moduleframework/tools/helpmd_lint.py#L30
https://github.com/fedora-modularity/meta-test-family/blob/devel/moduleframework/helpfile_linter.py

It would be nice to add also possibility for roff format.

MTF will not check roff format in container/image. This is case for conu. Therefore reassigning.
MTF issue is here: https://github.com/fedora-modularity/meta-test-family/issues/138

**Comment by TomasTomecek** [comment]
I'm +1 on having code in conu which checks whether a help file is present in a container (image).

I'm -1 on the code which parses the help file, be it roff or markdown. Maintaining such code is completely infeasible from my PoV. If you have some good arguments here, I would like to hear them.

**Comment by phracek** [comment]
@TomasTomecek Yes, checking only presence of help file is fine. And I guess only roff file has to be used in container(image). I would check only sections like:

```
.TH "MEMCACHED"
.SH NAME
.SH DESCRIPTION
.SH USAGE
.SH ENVIRONMENT VARIABLES
.SH SECURITY IMPLICATIONS
```
Some of them are invalid if e.g. environment variables does not exist in Dockerfile or even they are not specified.

**Comment by dhodovsk** [comment]
AC: implement basic method for checking existence of help file and for getting help file. Those methods then will be used in external linter or mtf.

**Comment by TomasTomecek** [comment]
Agreed that this may no longer be needed.

**Comment by dhodovsk** [comment]
This will be done in colin https://github.com/user-cont/colin/issues/83
