### ISSUE TITLE
improve UX using backend

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/conu#144]
Right now the [clean](https://github.com/fedora-modularity/conu/blob/master/conu/apidefs/backend.py#L118) method of backend is private. I think we should promote it to be public and provide docs on how to use backend w/o context managers. Something like:

```python
try:
  backend = ...
  backend.initia...
finnaly:
  backend.clean()
```

Dominika's suggestion:
* [ ] document in readme

**Comment by dhodovsk** [comment]
Please reopen if you feel you need this.
