### ISSUE TITLE
High-level helper functions for k8s/OpenShift

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/conu#160]
Recently we created [a new submodule](https://github.com/fedora-modularity/conu/pull/154) which contains high-level functions which you can utilize while writing tests for your containers. At the moment these functions can be used only for standalone containers.

We would love if conu was able to handle orchestrated deployments (=k8s/openshift) as well. Therefore this issue should add support for high-level functions which can be utilized to validate your containerized applications deployed in an orchestrated manner.

Some of these high-level functions may include:
 * Scale the deployment and verify it works well.
 * Update a service and verify it was updated correctly.
 * Healthcheck support: add an easy way for test authors to create custom healthchecks.
 * Verify that connection between two services works well (e.g. database and a client).
 * Seamless testing for webservers.

And more... While working on this, it's expected that you would invent new ones.

## Detailed plan

The plan here is simple:
1. Pick a container image which is being delivered as part of Fedora project
2. Prepare a test scenario when the service is deployed in an orchestrated environment. Utilize some high-level function (see above) in the scenario.
3. Propose the test scenario via an issue or pull request and let upstream developers of this repository to approve it.
4. Implement the high-level function and the test scenario.

Repeat this cycle for 10 times -- the container image and the test scenario may be recycled.

This issue is a detailed plan for [this GSoC theme](https://docs.fedoraproject.org/mentored-projects/gsoc/2018/ideas.html#advanced-test-cases-for-images-running-in-openshift-using-conu).

This issue is heavily related to #155.

**Comment by dhodovsk** [comment]
Partially done by @rpitonak as part of GSoC, the work will continue.
