### ISSUE TITLE
Add check environment method to backend initialization

### ISSUE THREAD

**Issue by dhodovsk** [user-cont/conu#174]
Based on discussion with @TomasTomecek  and @jscotka:

Backends can have different requirements for environment:
 - running processes (docker, systemd,...)
 - installed packages (s2i, machinectl, brtfs,...).

Add method to every existing backend which checks this and  when some of the checks fail, throw an exception and provide link to documentation.

Wild idea: Follow up of this issue might be ansible-playbook for every backend which prepares the enviroment - so the checks can pass.

**Comment by jscotka** [comment]
Hi, this could look like: static method for each class, and ``super`` class will call back that like:
https://github.com/fedora-modularity/conu/blob/master/conu/backend/nspawn/image.py#L56

**Comment by dhodovsk** [comment]
There are many methods in conu.utils that can be used for this purpose (e.g. https://github.com/user-cont/conu/blob/master/conu/utils/__init__.py#L171).
