### ISSUE TITLE
Create Image instance from id

### ISSUE THREAD

**Issue by lachmanfrantisek** [user-cont/conu#185]
It would be useful to be able to create an instance of `DockerImage` from its `id` without name or tag.

Any ideas how to edit parameters to not break the backward compatibility?

```
class DockerImage(Image):
    def __init__(self, repository, tag="latest", pull_policy=DockerImagePullPolicy.IF_NOT_PRESENT):
```
> Usecase: Loading image class from colin, when the user set the image-id isntead of the name.

Some questions:

- What will be the `get_full_name` of the image created from the id?
    - None
    - id
    - Try to find one from metadata?
- Try same approach for containers?
- When we are in this, we can provide better work with image names in general. What about something like [in atomic_reactor](https://github.com/projectatomic/atomic-reactor/blob/master/atomic_reactor/util.py#L57)?

**Comment by TomasTomecek** [comment]
> What will be the get_full_name of the image created from the id? 

`None`, ideally use id instead of name. For pull, we could do on-demand lookup for the name via metadata.

> Try same approach for containers?

Yes.

> we can provide better work with image names in general

Yup, that's gonna be a tough one.

**Comment by dhodovsk** [comment]
This has been resolved in https://github.com/user-cont/colin/pull/54
