### ISSUE TITLE
add CONTRIBUTING.md

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/conu#190]
originally suggested by @enriquetaso via e-mail conversation

* [x] setting up development environment
  * [x] conu dependencies
  * [x] testing dependencies (#189)
  * [x] user technologies/tools
* [x] preferred development workflow
  * [x] new feature
  * [x] bugfix
* [x] describe makefile
* [x] describe testing

**Comment by rpitonak** [comment]
I will close this one If you find some issues in CONTRIBUTING.md, or you have suggestions what to add, please open a new issue.
