### ISSUE TITLE
implement libpod/podman as a new backend

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/conu#200]
podman is a tool to run OCI-compliant containers. Since this is something Red Hat is advocating, we should add as a new backend in conu. Ideally, we would utilize skopeo as well.

The implementation in conu should be done using podman's python API: https://github.com/projectatomic/libpod/pull/748

**Comment by dhodovsk** [comment]
Take an inspiration from DockerBackend, use similar methods when possible, use the same UX, workflow...

**Comment by TomasTomecek** [comment]
Resolved by #298
