### ISSUE TITLE
run_via_binary,run_command: pipe outputs

### ISSUE THREAD

**Issue by TomasTomecek** [user-cont/conu#211]
we should pipe stdout and stderr of run_command and log it, instead of printing to output directly so colin has prettier output:

no
```
3e357036cbf2ac54d6bc62314e563608c125a8e443366f5f047dab88c7cb3606
PASS:Shell has to be runnable.

PASS:1 
```

yes
```
PASS:Shell has to be runnable.

PASS:1 
```

**Comment by SkullTech** [comment]
I'm thinking of working on this. Should I implement the change in the `run_cmd` function itself? That way for 
_every_ call to `run_cmd`—not only the ones from `run_via_binary`—it will redirect the `STDOUT` and `STDERR` to `logger`. Or should I do this only in the case of `run_via_binary`?

**Comment by TomasTomecek** [comment]
@SkullTech Thank you for your interest!

My preference would be to change `run_cmd` directly.

I would personally implement it using `.communicate()` method. `.check_output()` methods have problem that in case of an error, the output is lost.

**Comment by SkullTech** [comment]
@TomasTomecek It's a pleasure!

I was thinking of going with `.communicate()` too! Thanks for clearing my doubt.
