### ISSUE TITLE
AttributeError: module 'kubernetes.client' has no attribute 'AppsV1Api'

### ISSUE THREAD

**Issue by jpopelka** [user-cont/conu#240]
```
$ pip3 list | grep kubernetes
kubernetes        6.0.0
```

@rpitonak I know we already asked about this, but I don't remember what was your suggestion how to make this work.

**Comment by rpitonak** [comment]
It depends also on version of kubernetes cluster running on host (in minikube). See [compatibility matrix](https://github.com/kubernetes-client/python#compatibility)

You can try to reproduce these steps to test it locally:
```
rm -rf ~/.minikube
minikube delete
minikube start --kubernetes-version=v1.10.0
make container-image
make test-k8s-minikube
```

**Comment by jpopelka** [comment]
I forgot to add that I see this when I run `make test`, which does not include the test-k8s-minikube target.
Do I need to also start minikube before `make test` ?

**Comment by jpopelka** [comment]
Something was probably stale on my system, I did some rebuilds and don't see this anymore. Closing.
