### ISSUE TITLE
Provide more advanced example of using k8s

### ISSUE THREAD

**Issue by rpitonak** [user-cont/conu#246]
In #244 we introduced simple example of how to use k8s backend.

Would be awesome to have more advanced one, including resolving issues or inspection.

**Comment by dhodovsk** [comment]
One example here https://github.com/user-cont/conu/pull/273/commits/5eadf52fa3fd4f81b41d75f5df90944ac5c74e87

**Comment by rpitonak** [comment]
We have more examples now and also interactive notebook here https://github.com/rpitonak/conu-devconf.
