### ISSUE TITLE
Unable to install directly from repo

### ISSUE THREAD

**Issue by SkullTech** [user-cont/conu#257]
When trying to install `conu` directly from the this repo—using any of the below mentioned methods—the command fails throwing an error like the following —

_Installation methods_

- `$ pip3 install --user .`
- `$ python3 setup.py install`
- `$ pip3 install git+git://github.com/user-cont/conu.git`

_Error message_
```console
[sumit@hal9000 conu]$ pip3 install --user .
Processing /home/sumit/Coding/conu
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-lf6poj06-build/setup.py", line 75, in <module>
        install_requires=get_requirements()
      File "/tmp/pip-lf6poj06-build/setup.py", line 35, in get_requirements
        with open("./requirements.txt") as fd:
    FileNotFoundError: [Errno 2] No such file or directory: './requirements.txt'
...
```

It's clear that it's happening because `setup.py` still contains a reference to a `requirements.txt`, but it was renamed to `requirements.in`. I'm not entirely sure why it was done, I know it was done because of the `Kebechet` integration, but doesn't `Kebechet` also support the `.txt` file extension for the _requirements_ file?

Fixing it would be simple anyway, just changing the reference in `setup.py` to that of `requirements.in`. But I just wanted to ask if we should revert to using the `txt` extension, it's pretty much the standard.

Either way, I can start a pull-request. Just let me know which path should we take. Excited to start contributing to this project :)

**Comment by fridex** [comment]
This should be fixed with https://github.com/user-cont/conu/pull/253

**Comment by TomasTomecek** [comment]
Sorry about this, should be fixed now. Let us know if you still have problems.
