### ISSUE TITLE
xattr dependency

### ISSUE THREAD

**Issue by lachmanfrantisek** [user-cont/conu#281]
When installing conu from the PyPI, the `xattr` package is not installed.

```
/usr/lib/python3.6/site-packages/conu/backend/docker/container.py:35: in <module>
    from conu.apidefs.filesystem import Filesystem
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

    import logging
    import os
    import shutil
>   import xattr
E   ModuleNotFoundError: No module named 'xattr'
```

Is adding `xattr` to [requirements.txt](https://github.com/user-cont/conu/blob/master/requirements.txt) enough?

----

Or make it optional?

**Comment by TomasTomecek** [comment]
My vote:
 * add correct xattr in specfile so that it gets installed when running conu from RPM repositories
 * do not add it to req.txt
 * wrap `import xattr` in try/catch and raise appropriate exception when someone tries to use functionality which requires xattr

Opinions?
