### ISSUE TITLE
Testing in VM fails

### ISSUE THREAD

**Issue by fasashen** [user-cont/conu#308]
**Running `make test-in-vm` or `vagrant up` doesn't pass the docker tests.**

It fails in tries to prepare docker containers and images in `conftest.py`, when it execs command inside a container: 
`docker container run --name nc-container registry.fedoraproject.org/fedora-minimal:26 microdnf install nmap-ncat`

> subprocess.CalledProcessError: Command '['docker', 'container', 'run', '--name', 'nc-container', 'registry.fedoraproject.org/fedora-minimal:26', 'microdnf', 'install', 'nmap-ncat']' returned non-zero exit status 137.

I've tested it on both macOS and Windows machines and it just throws this message every time. So to avoid it I manually create containers for test purposes, so pytest skips this line.

**Comment by fasashen** [comment]
Sorry, the issue is solved in PR #307.

**Comment by TomasTomecek** [comment]
No worries, glad it's resolved now.
