### ISSUE TITLE
Fedora installation problems

### ISSUE THREAD

**Issue by lachmanfrantisek** [user-cont/conu#341]
There is a problem with conu dependances in fedora.

Since colin CLI (click) checks the dependences on each start, only being dependant on conu makes colin CLI unusable.

See https://github.com/user-cont/colin/issues/216

**Comment by TomasTomecek** [comment]
What's the version of conu?

**Comment by lachmanfrantisek** [comment]
```
python3-conu-0.6.2-1.fc28.noarch
python3-conu-0.6.2-1.fc29.noarch
```

**Comment by TomasTomecek** [comment]
Okay, so our specfiles are out of sync, upstream works okay.
