### ISSUE TITLE
Change licence from GPLv3 to MIT

### ISSUE THREAD

**Issue by jpopelka** [user-cont/conu#379]
[We](https://github.com/orgs/user-cont/teams/the-team) have decided to change conu's license from GPLv3 to (more permissive) MIT.

I'd like to hear from all the contributors whether they are OK with the change.

@rpitonak @dhodovsk @palusus @fasashen @phracek @jhrdt @SkullTech @enriquetaso @fridex @kmehant @hroncok 
speak now or forever hold your peace :wink: 

Thanks

**Comment by fridex** [comment]
+1 on my side

**Comment by hroncok** [comment]
Feel free to relicense my contribution here as you see fit, I consider it trivial.


> speak now or forever hold your peace

I am afraid this is not how copyright works.

**Comment by TomasTomecek** [comment]
You have my permission.

**Comment by jhrdt** [comment]
You have my permission.

**Comment by dhodovsk** [comment]
I'm OK with the change

**Comment by lachmanfrantisek** [comment]
You have my permission.

**Comment by fasashen** [comment]
You have my permission.

**Comment by palusus** [comment]
I have no problem with that.
